epc <- read.table(file="household_power_consumption.txt", header=TRUE, sep=";")
GAP1 <- subset(epc, select = c(Date, Time, Global_active_power), subset = (Date == "1/2/2007"))
GAP2 <- subset(epc, select = c(Date, Time, Global_active_power), subset = (Date == "2/2/2007"))
GAP12 <- rbind(GAP1, GAP2)
a <- as.character(GAP12[,1])
b <- as.character(GAP12[,2])
d <- paste(a, b)
e <- strptime (d, format = "%d/%m/%Y %H:%M:%S", tz = "GMT")
GAP <- as.numeric(as.character(GAP12[,3]))
Sys.setlocale("LC_TIME","English")
weekdays(Sys.Date()+1:3)
plot(e, GAP, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.copy(png, file = "plot2.png")
dev.off()