epc <- read.table(file="household_power_consumption.txt", header=TRUE, sep=";")
ESM1 <- subset(epc, select = c(Date, Time, Sub_metering_1, Sub_metering_2, Sub_metering_3), subset = (Date == "1/2/2007"))
ESM2 <- subset(epc, select = c(Date, Time, Sub_metering_1, Sub_metering_2, Sub_metering_3), subset = (Date == "2/2/2007"))
ESM12 <- rbind(ESM1, ESM2)
a <- as.character(ESM12[,1])
b <- as.character(ESM12[,2])
d <- paste(a, b)
Sys.setlocale("LC_TIME","English")
weekdays(Sys.Date()+1:3)
e <- strptime (d, format = "%d/%m/%Y %H:%M:%S", tz = "GMT")
x1 <- as.numeric(as.character(ESM12[,3]))
x2 <- as.numeric(as.character(ESM12[,4]))
x3 <- as.numeric(as.character(ESM12[,5]))
plot(e, x1, type = "l", xlab = "", ylab = "Energy sub metering", col ="black", ylim = c(0, max(x1)))
par(new=T)
plot(e, x2, type = "l", xlab = "", ylab = "Energy sub metering", col ="red", ylim = c(0, max(x1)))
par(new=T)
plot(e, x3, type = "l", xlab = "", ylab = "Energy sub metering", col ="blue", ylim = c(0,max(x1)))
legend("topright", cex = 0.9, xjust = 1, yjust = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), bty = "o", lty = 1)
dev.copy(png, file = "plot3.png")
dev.off()
