epc <- read.table(file="household_power_consumption.txt", header=TRUE, sep=";", col.names=c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
GAP1 <- subset(epc, select = Global_active_power, subset = (Date == "1/2/2007"))
GAP2 <- subset(epc, select = Global_active_power, subset = (Date == "2/2/2007"))
GAP12 <- rbind(GAP1, GAP2)
GAP <- as.numeric(as.character(GAP12[,1]))
hist(GAP, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "red" )
dev.copy(png, file = "plot1.png")
dev.off()